### ISSUE TITLE
Missing Table Exception

### ISSUE THREAD

**Issue by gabrielpiccolo4** [govbr/suindara.govbr#1]
Foi instalado e configurado corretamente o CMS Suindara em um Ubuntu 15.10, todavia, após criar o primeiro usuário que acessará o sistema, ele tenta abrir a página "http://website.com/Fontes/admin", e é retornado um "Internal Error Has Occurred.". Segue abaixo o meu arquivo de Log disposto em "/var/www/website.com/public_html/Fontes/app/tmp/logs".

2015-11-30 09:42:35 Error: [MissingTableException] Table **configuracaos** for model Configuracao was not found in datasource default.
Exception Attributes: array (
  'table' => 'configuracaos',
  'class' => 'Configuracao',
  'ds' => 'default',
)
Request URL: /Fontes/admin
Stack Trace:
#0 /var/www/website.com/public_html/Fontes/lib/Cake/Model/Model.php(3231): Model->setSource('configuracaos')
#1 /var/www/website.com/public_html/Fontes/lib/Cake/Model/Model.php(2688): Model->getDataSource()
#2 /var/www/website.com/public_html/Fontes/lib/Cake/Model/Datasource/CakeSession.php(556): Model->find('first', Array)
#3 /var/www/website.com/public_html/Fontes/lib/Cake/Model/Datasource/CakeSession.php(468): CakeSession::_defaultConfig('php')
#4 /var/www/website.com/public_html/Fontes/lib/Cake/Model/Datasource/CakeSession.php(203): CakeSession::_configureSession()
#5 /var/www/website.com/public_html/Fontes/lib/Cake/Model/Datasource/CakeSession.php(230): CakeSession::start()
#6 /var/www/website.com/public_html/Fontes/lib/Cake/Controller/Component/AuthComponent.php(597): CakeSession::check('Auth.User')
#7 /var/www/website.com/public_html/Fontes/app/Lib/Cms/CmsController.php(179): AuthComponent::user()
#8 /var/www/website.com/public_html/Fontes/app/Core/Usuarios/Controller/UsuariosController.php(643): CmsController->beforeFilter()
#9 [internal function]: UsuariosController->beforeFilter(Object(CakeEvent))
#10 /var/www/website.com/public_html/Fontes/lib/Cake/Event/CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#11 /var/www/website.com/public_html/Fontes/lib/Cake/Controller/Controller.php(670): CakeEventManager->dispatch(Object(CakeEvent))
#12 /var/www/website.com/public_html/Fontes/lib/Cake/Routing/Dispatcher.php(184): Controller->startupProcess()
#13 /var/www/website.com/public_html/Fontes/lib/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#14 /var/www/website.com/public_html/Fontes/app/webroot/index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

Abaixo uma foto das tabelas do banco de dados no MySQL Workbench:
![tabelas](https://cloud.githubusercontent.com/assets/10145361/11470743/62356fba-9747-11e5-9fa4-b2a07b33cab0.png)

**Comment by laelNervis** [comment]
Olá Gabriel,
Acreditamos ter corrigido os problemas. Realizamos testes em diferentes ambientes onde as instalações funcionaram corretamente.
Caso ocorra algum outro problema, nos reporte, estamos a disposição.
Atenciosamente.
