### ISSUE TITLE
Call to undefined function imagecreatefromjpeg()

### ISSUE THREAD

**Issue by gabrielpiccolo4** [govbr/suindara.govbr#2]
Ao inserir uma imagem no banco de dados é retornado o erro "Call to undefined function imagecreatefromjpeg()" (página de erro abaixo).

[Página HTML com o erro.zip](https://github.com/govbr/suindara.govbr/files/63987/Erro.ao.inserir.imagem.JPG.zip)

![screenshot_pagadmin](https://cloud.githubusercontent.com/assets/10145361/11841391/2e5562aa-a3e4-11e5-88d5-f6938aea6b15.png)

**Comment by laelNervis** [comment]
Olá @gabrielpiccolo4,

Primeiramente peço desculpas pela demora no retorno. Nossa equipe estava de férias. Corrigimos este bug. Comitamos os arquivos ontem.

Qualquer problema pode reportar.

Atenciosamente
